chore(vote): Fix Linter issues and add Coverage

diff --git a/.github/workflows/python-app.yaml b/.github/workflows/python-app.yaml
--- a/.github/workflows/python-app.yaml
+++ b/.github/workflows/python-app.yaml
@@ -9,6 +9,8 @@ permissions:
 
 jobs:
   build:
+    permissions:
+      checks: write
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -25,7 +27,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install flake8 pytest
+          pip install flake8 pytest pytest-cov
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
 
       - name: Lint with flake8
@@ -36,10 +38,43 @@ jobs:
           flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
 
       - name: Test with pytest
+        id: pytest
         run: |
-          pytest
+          test_results="${PWD}/test-results.xml"
+          pytest --junit-xml "${test_results}"
+
+          # Generate Output
+          echo "report_paths=${test_results}" | tee -a $GITHUB_OUTPUT
         env:
           PYTHONPATH: ${{ github.workspace }}/vote
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: ${{ steps.pytest.outputs.report_paths }}
+          detailed_summary: true
+          include_passed: true
+
+      - name: Generate Coverage
+        id: coverage
+        run: |
+          pytest --cov --cov-report=xml
+
+          # Expose Coverage path
+          path=$(realpath --relative-to=${{ github.workspace }} coverage.xml)
+          echo "path=${path}" | tee -a $GITHUB_OUTPUT
+        env:
+          PYTHONPATH: ${{ github.workspace }}/vote
+
+      - name: Publish Coverage
+        uses: 5monkeys/cobertura-action@master
+        with:
+          path: ${{ steps.coverage.outputs.path }}
+          minimum_coverage: 70
+          fail_below_threshold: true
+          show_line: true
+          show_branch: true
 
       - name: Check Dirty Repository
         run: |
